name: Prek Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Run Prek checks
        uses: j178/prek-action@564dda4cfa5e96aafdc4a5696c4bf7b46baae5ac # v1
        with:
          extra-args: --skip hadolint-docker
