name: Prek Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run Prek checks
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1
        with:
          extra-args: --skip hadolint-docker
