name: Prek Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run Prek checks
        uses: j178/prek-action@564dda4cfa5e96aafdc4a5696c4bf7b46baae5ac # v1
        with:
          extra-args: --skip hadolint-docker
